= API Reference

:toc:

== ethrpc.net

=== ethrpc.net.version 
Returns the current network id

.Parameters
none

.Returns
`Promise` returns `String` :  The current network id.

* `"1"` - Ethereum Classic mainnet
* `"2"` - Morden Testnet

.Example
[source,javascript]
----
ethrpc.net.version()
    .then(console.log)
> 1
----

=== ethrpc.net.listening 
Returns `true` if client is actively listening for network connections.

.Parameters
none

.Returns
`Promise` returns `Boolean`

.Example
[source,javascript]
----
ethrpc.net.listening()
    .then(console.log)
> true
----

=== ethrpc.net.peerCount 
Returns number of peers currently connected to the client.

.Parameters
none

.Returns
`Promise` returns `number`

.Example
[source,javascript]
----
ethrpc.net.peerCount()
    .then(console.log)
> 33
----


== ethrpc.eth

=== ethrpc.eth.protocolVersion 
Returns the current Ethereum protocol version

.Parameters
none

.Returns
`Promise` returns `String` :  The current ethereum protocol version

.Example
[source,javascript]
----
ethrpc.eth.protocolVersion()
    .then(console.log)
> 0x3f
----

=== ethrpc.eth.getBalance
```
getBalance(address, [blockNumber]) 
```

Returns the balance of the account of given address


.Parameters
1. `String` - The address to get the balance of.
2. `String | Number` - (optional) Default value `latest`

.Returns
`Promise` returns `BigNumber` :  The current balance for the given address in wei.

.Example
[source,javascript]
----
ethrpc.eth.getBalance('0x0000000000000000000000000000000000000000')
  .then(balance => {
    console.log(balance.toString(10)); // 7226493586402062545566
    console.log(balance.toNumber()); // 7.226493586402063e+21
  });
----

=== ethrpc.eth.gasPrice
```
gasPrice() 
```

Returns the current gas price. The gas price is determined by the last few blocks median gas price.


.Parameters
none

.Returns
`Promise` returns `BigNumber` :  A BigNumber instance of the current gas price in wei

.Example
[source,javascript]
----
ethrpc.eth.gasPrice()
  .then(price => {
    console.log(price.toString(10)); // 20000000000
  });
----

=== ethrpc.eth.getSyncing()
```
getSyncing() 
```

Returns an object with data about the sync status or false.


.Parameters
none

.Returns
`Promise` returns `Object|Boolean` :  A sync object as follows, when the node is currently syncing or `false`

* `startingBlock: Number` - The block number where the sync started.
* `currentBlock: Number` - The block number where at which block the node currently synced to already.
* `highestBlock: Number` - The estimated block number to sync to.


.Example
[source,javascript]
----
ethrpc.eth.getSyncing()
  .then(result => {
  ...
  });
----

=== ethrpc.eth.getBlock()
```
 getBlock(blockHashOrBlockNumber [, includeTxs])

```

Returns a block matching the block number or block hash.


.Parameters

1. `String|Number` - The block number or hash. Or the string "earliest", "latest" or "pending" as in the default block parameter.
2. `Boolean` - (optional, default false) If true, the returned block will contain all transactions as objects, if false it will only contains the transaction hashes.


.Returns
`Promise` returns `Object` : The block object


* number: Number - the block number. null when its pending block.
* hash: String, 32 Bytes - hash of the block. null when its pending block.
* parentHash: String, 32 Bytes - hash of the parent block.
* nonce: String, 8 Bytes - hash of the generated proof-of-work. null when its pending block.
* sha3Uncles: String, 32 Bytes - SHA3 of the uncles data in the block.
* logsBloom: String, 256 Bytes - the bloom filter for the logs of the block. null when its pending block.
* transactionsRoot: String, 32 Bytes - the root of the transaction trie of the block
* stateRoot: String, 32 Bytes - the root of the final state trie of the block.
* miner: String, 20 Bytes - the address of the beneficiary to whom the mining rewards were given.
* difficulty: BigNumber - integer of the difficulty for this block.
* totalDifficulty: BigNumber - integer of the total difficulty of the chain until this block.
* extraData: String - the "extra data" field of this block.
* size: Number - integer the size of this block in bytes.
* gasLimit: Number - the maximum gas allowed in this block.
* gasUsed: Number - the total used gas by all transactions in this block.
* timestamp: Number - the unix timestamp for when the block was collated.
* transactions: Array - Array of transaction objects, or 32 Bytes transaction hashes depending on the last given parameter.
* uncles: Array - Array of uncle hashes.


.Example
[source,javascript]
----
 TODO
----